version: '3.5'

services:
  meilisearch:
    restart: always
    image: getmeili/meilisearch:v1.2
    depends_on:
      - db
      - django
    networks:
      - app_network
    ports:
      - "7700:7700"
    volumes:
      - ./meilisearch_data:/data.ms
    env_file:
      - .env
    environment:
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
  db:
    restart: always
    image: postgres:15.3
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - app_network
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  redis:
    restart: always
    image: redis:7.0.8
    networks:
      - redis_network

  django:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DJANGO_SECRET_KEY
    depends_on:
      - db
      - redis
    command: gunicorn learn_serbian.wsgi -c gunicorn.cfg.py
    volumes:
      - ./_app:/usr/src/app
    networks:
      - app_network
      - redis_network
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=0

volumes:
  database_volume:

networks:
  app_network:
  redis_network:
