# Generated by Django 4.2.1 on 2023-05-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_savedword_watched_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedword',
            name='watched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
