# Generated by Django 4.2.1 on 2023-05-31 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_lesson_saved_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedword',
            name='deleted',
        ),
    ]
