# Generated by Django 4.2.1 on 2023-05-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_category_word_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
