# Generated by Django 4.2.1 on 2023-05-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttranslation',
            name='lang',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], max_length=3),
        ),
        migrations.AlterField(
            model_name='translation',
            name='lang',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], max_length=3),
        ),
    ]
