# Generated by Django 4.2.1 on 2023-05-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_alter_texttranslation_lang_alter_translation_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='category',
            name='texts',
            field=models.ManyToManyField(related_name='categories', to='words.text'),
        ),
        migrations.AddField(
            model_name='category',
            name='words',
            field=models.ManyToManyField(related_name='categories', to='words.word'),
        ),
    ]
