# Generated by Django 4.2.1 on 2023-05-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0010_remove_word_categories_category_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='tags',
            field=models.ManyToManyField(related_name='words', to='words.tag'),
        ),
    ]
