# Generated by Django 4.2.1 on 2023-05-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0013_alter_category_texts_alter_category_words'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
