# Generated by Django 4.2.1 on 2023-05-31 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0016_delete_savedword'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='s3_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
