# Generated by Django 4.2.1 on 2023-05-24 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0013_alter_category_texts_alter_category_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media')),
                ('texts', models.ManyToManyField(blank=True, related_name='topics', to='words.text')),
                ('words', models.ManyToManyField(blank=True, related_name='topics', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='TopicTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lang', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], max_length=3)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='topics.topic')),
            ],
        ),
    ]
