# Generated by Django 4.2.2 on 2023-06-14 19:13

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_lang_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media', validators=[accounts.models.validate_image_size]),
        ),
    ]
